{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1061349a",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Set random seed for reproducibility\n",
    "np.random.seed(42)\n",
    "\n",
    "# ==========================================================\n",
    "# FUNCTION TO GENERATE LINEARLY SEPARABLE DATA\n",
    "# ==========================================================\n",
    "def generate_data(N):\n",
    "\n",
    "    # Random target function:\n",
    "    # w0 + w1*x1 + w2*x2 = 0\n",
    "    w_true = np.random.randn(3, 1)\n",
    "\n",
    "    # Generate N random points\n",
    "    X = np.random.uniform(-10, 10, (N, 2))\n",
    "\n",
    "    # Add bias term x0 = 1\n",
    "    X_bias = np.hstack((np.ones((N, 1)), X))\n",
    "\n",
    "    # Assign class labels using target function\n",
    "    y = np.sign(X_bias @ w_true)\n",
    "\n",
    "    # Replace zero labels with +1\n",
    "    y[y == 0] = 1\n",
    "\n",
    "    return X, X_bias, y, w_true\n",
    "\n",
    "\n",
    "# ==========================================================\n",
    "# PERCEPTRON LEARNING ALGORITHM\n",
    "# ==========================================================\n",
    "def perceptron(X_bias, y):\n",
    "\n",
    "    # Number of samples and features\n",
    "    N, d = X_bias.shape\n",
    "\n",
    "    # Initialize weight vector with zeros\n",
    "    w = np.zeros((d, 1))\n",
    "\n",
    "    # Count updates\n",
    "    updates = 0\n",
    "\n",
    "    while True:\n",
    "\n",
    "        error_count = 0\n",
    "\n",
    "        # Check every training example\n",
    "        for i in range(N):\n",
    "\n",
    "            # If point is misclassified\n",
    "            if y[i] * (X_bias[i].reshape(1, -1) @ w) <= 0:\n",
    "\n",
    "                # Update weight vector\n",
    "                w += y[i] * X_bias[i].reshape(-1, 1)\n",
    "\n",
    "                updates += 1\n",
    "                error_count += 1\n",
    "\n",
    "        # Stop when no errors remain\n",
    "        if error_count == 0:\n",
    "            break\n",
    "\n",
    "    return w, updates\n",
    "\n",
    "\n",
    "# ==========================================================\n",
    "# FUNCTION TO PLOT RESULTS\n",
    "# ==========================================================\n",
    "def plot_results(X, y, w_true, w_final, title):\n",
    "\n",
    "    plt.figure(figsize=(7, 7))\n",
    "\n",
    "    # Plot positive and negative examples\n",
    "    for i in range(len(y)):\n",
    "\n",
    "        if y[i] == 1:\n",
    "            plt.scatter(\n",
    "                X[i, 0],\n",
    "                X[i, 1],\n",
    "                marker='o'\n",
    "            )\n",
    "        else:\n",
    "            plt.scatter(\n",
    "                X[i, 0],\n",
    "                X[i, 1],\n",
    "                marker='x'\n",
    "            )\n",
    "\n",
    "    # Values for drawing lines\n",
    "    x_vals = np.linspace(-10, 10, 100)\n",
    "\n",
    "    # Plot target function f\n",
    "    y_true_line = -(w_true[0] +\n",
    "                    w_true[1] * x_vals) / w_true[2]\n",
    "\n",
    "    plt.plot(\n",
    "        x_vals,\n",
    "        y_true_line,\n",
    "        label=\"Target Function f\"\n",
    "    )\n",
    "\n",
    "    # Plot learned hypothesis g\n",
    "    y_final_line = -(w_final[0] +\n",
    "                     w_final[1] * x_vals) / w_final[2]\n",
    "\n",
    "    plt.plot(\n",
    "        x_vals,\n",
    "        y_final_line,\n",
    "        linestyle='--',\n",
    "        label=\"Final Hypothesis g\"\n",
    "    )\n",
    "\n",
    "    plt.xlabel(\"x1\")\n",
    "    plt.ylabel(\"x2\")\n",
    "\n",
    "    plt.title(title)\n",
    "\n",
    "    plt.legend()\n",
    "    plt.grid(True)\n",
    "\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "# ==========================================================\n",
    "# CASE 1 : DATASET SIZE = 20\n",
    "# ==========================================================\n",
    "\n",
    "N1 = 20\n",
    "\n",
    "# Generate dataset\n",
    "X1, X1_bias, y1, w_true1 = generate_data(N1)\n",
    "\n",
    "# Train perceptron\n",
    "w_final1, updates1 = perceptron(\n",
    "    X1_bias,\n",
    "    y1\n",
    ")\n",
    "\n",
    "# Display number of updates\n",
    "print(\"Dataset Size = 20\")\n",
    "print(\"Number of Updates Before Convergence:\",\n",
    "      updates1)\n",
    "\n",
    "# Plot dataset, target function and hypothesis\n",
    "plot_results(\n",
    "    X1,\n",
    "    y1,\n",
    "    w_true1,\n",
    "    w_final1,\n",
    "    \"Perceptron Learning (N = 20)\"\n",
    ")\n",
    "\n",
    "\n",
    "# ==========================================================\n",
    "# CASE 2 : DATASET SIZE = 100\n",
    "# ==========================================================\n",
    "\n",
    "N2 = 100\n",
    "\n",
    "# Generate dataset\n",
    "X2, X2_bias, y2, w_true2 = generate_data(N2)\n",
    "\n",
    "# Train perceptron\n",
    "w_final2, updates2 = perceptron(\n",
    "    X2_bias,\n",
    "    y2\n",
    ")\n",
    "\n",
    "# Display number of updates\n",
    "print(\"\\nDataset Size = 100\")\n",
    "print(\"Number of Updates Before Convergence:\",\n",
    "      updates2)\n",
    "\n",
    "# Plot dataset, target function and hypothesis\n",
    "plot_results(\n",
    "    X2,\n",
    "    y2,\n",
    "    w_true2,\n",
    "    w_final2,\n",
    "    \"Perceptron Learning (N = 100)\"\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
